name: music_player
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  on_audio_query: ^2.6.1
  permission_handler: ^10.2.0
  just_audio: ^0.9.30
  just_audio_background: ^0.0.1-beta.8
  fluttertoast: ^8.1.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

